paas_app_fe_name          = "monitor-my-satellites-fe-dev"
paas_app_api_name         = "monitor-my-satellites-api-dev"
paas_app_route_name       = "monitor-my-satellites-dev"
paas_app_api_route_name   = "monitor-my-satellites-api-dev"
paas_db_name              = "monitor-my-satellites-db-dev"
paas_s3_name              = "monitor-my-satellites-s3-dev"
paas_space                = "monitor-my-satellites-dev"