name: Deploy to PaaS
on:
  workflow_dispatch:
    inputs:
      invoker:
        description: 'Invoker'
        required: true
        default: ''
      env:
        description: 'Environment'
        required: false
        default: 'dev'

jobs:
  called_with_by:
    name: Called by who? And with what?
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Calling ${{ github.event.inputs.env }} from ${{ github.event.inputs.invoker }}!"

  deploy:
    needs: called_with_by
    name: Deploy to Gov.UK PaaS
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.env }}

    steps:
      - uses: hashicorp/setup-terraform@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="key=${{ secrets.s3_backend_key }}" \
            -backend-config="region=${{ secrets.s3_backend_region }}" \
            -backend-config="bucket=${{ secrets.s3_backend_bucket }}" \
            -backend-config="access_key=${{ secrets.s3_access_key }}" \
            -backend-config="secret_key=${{ secrets.s3_secret_key }}"