name: Deploy to PaaS
on:
  workflow_dispatch:
    inputs:
      invoker:
        description: 'Invoker'
        required: true
        default: ''
      env:
        description: 'Environment'
        required: false
        default: 'dev'

jobs:
  called_with_by:
    name: Objective
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "Deploy ${{ github.event.inputs.invoker }} on ${{ github.event.inputs.env }}"

  deploy:
    needs: called_with_by
    name: Deploy to Gov.UK PaaS
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.environments }}
    concurrency: ${{ github.event.inputs.environments }}

    steps:
      - uses: hashicorp/setup-terraform@v1

      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform Init
        run: |
          terraform init \
            -reconfigure \
            -backend-config="key=${{ secrets.s3_backend_key }}" \
            -backend-config="region=${{ secrets.s3_backend_region }}" \
            -backend-config="bucket=${{ secrets.s3_backend_bucket }}" \
            -backend-config="access_key=${{ secrets.s3_backend_access_key }}" \
            -backend-config="secret_key=${{ secrets.s3_backend_secret_key }}"

      - name: Terraform Plan
        if: ${{ github.event.inputs.invoker == 'plan' }}
        run: |
          terraform plan \
            -var-file="${{ secrets.env_tfvars }}" \
            -var="paas_username=${{ secrets.paas_username }}" \
            -var="paas_password=${{ secrets.paas_password }}" \
            -var="github_token=${{ secrets.tf_github_token }}" \
            -var="logit_endpoint=${{ secrets.logit_endpoint }}" \
            -var="spacetrack_username=${{ secrets.spacetrack_username }}" \
            -var="spacetrack_password=${{ secrets.spacetrack_password }}" \
            -var="paas_app_iron_name=${{ secrets.paas_app_iron_name }}" \
            -var="paas_app_iron_password=${{ secrets.paas_app_iron_password }}" \
            -var="notify_api_key=${{ secrets.notify_api_key }}" \
            -var="user_service_jwt_authentication_secret=${{ secrets.user_service_jwt_authentication_secret }}" \
            -var="user_service_reset_password_token_secret=${{ secrets.user_service_reset_password_token_secret }}" \
            -var="user_service_verification_token_secret=${{ secrets.user_service_verification_token_secret }}"

      - name: Terraform Apply
        if: ${{ github.event.inputs.invoker == 'apply' }} || ${{ github.event.inputs.invoker == 'back-end' }} || ${{ github.event.inputs.invoker == 'front-end' }}
        run: |
          terraform apply \
            -auto-approve \
            -var-file="${{ secrets.env_tfvars }}" \
            -var="paas_username=${{ secrets.paas_username }}" \
            -var="paas_password=${{ secrets.paas_password }}" \
            -var="github_token=${{ secrets.tf_github_token }}" \
            -var="logit_endpoint=${{ secrets.logit_endpoint }}" \
            -var="spacetrack_username=${{ secrets.spacetrack_username }}" \
            -var="spacetrack_password=${{ secrets.spacetrack_password }}" \
            -var="paas_app_iron_name=${{ secrets.paas_app_iron_name }}" \
            -var="paas_app_iron_password=${{ secrets.paas_app_iron_password }}" \
            -var="notify_api_key=${{ secrets.notify_api_key }}" \
            -var="user_service_jwt_authentication_secret=${{ secrets.user_service_jwt_authentication_secret }}" \
            -var="user_service_reset_password_token_secret=${{ secrets.user_service_reset_password_token_secret }}" \
            -var="user_service_verification_token_secret=${{ secrets.user_service_verification_token_secret }}"

      - name: Terraform Destroy DB Migration
        if: ${{ github.event.inputs.invoker != 'plan' }}
        run: |
          terraform destroy \
            -target=module.back-end.cloudfoundry_app.db_migration \
            -auto-approve \
            -var-file="${{ secrets.env_tfvars }}" \
            -var="paas_username=${{ secrets.paas_username }}" \
            -var="paas_password=${{ secrets.paas_password }}" \
            -var="github_token=${{ secrets.tf_github_token }}" \
            -var="logit_endpoint=${{ secrets.logit_endpoint }}" \
            -var="spacetrack_username=${{ secrets.spacetrack_username }}" \
            -var="spacetrack_password=${{ secrets.spacetrack_password }}" \
            -var="paas_app_iron_name=${{ secrets.paas_app_iron_name }}" \
            -var="paas_app_iron_password=${{ secrets.paas_app_iron_password }}" \
            -var="notify_api_key=${{ secrets.notify_api_key }}" \
            -var="user_service_jwt_authentication_secret=${{ secrets.user_service_jwt_authentication_secret }}" \
            -var="user_service_reset_password_token_secret=${{ secrets.user_service_reset_password_token_secret }}" \
            -var="user_service_verification_token_secret=${{ secrets.user_service_verification_token_secret }}"
