name: Test e2e on dev env

on:
  push:
    branches:
      - feat-update-e2e-tests

jobs:

  deploy:
    needs: called_with_by
    name: Deploy to AWS
    runs-on: ubuntu-latest
    environment:
      name: 'dev'

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
      checks: write
      pull-requests: write

    steps:
      - uses: hashicorp/setup-terraform@v2

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Execute Backend E2E API tests
        uses: matt-ball/newman-action@master
        with:
          workingDir: aws/e2e_tests
          collection: aws/e2e_tests/postman_collection.json
          environment: aws/e2e_tests/postman_environment.json
          reporters: '["cli","junit"]'
          envVar: '[{ "key": "clientId", "value": "${{ secrets.e2e_client_id }}" },{ "key": "clientSecret", "value": "${{ secrets.e2e_client_secret }}" },{ "key": "baseUrl", "value": "${{ vars.e2e_base_url }}" },{ "key": "authBaseUrl", "value": "${{ vars.e2e_auth0_base_url }}" },{ "key": "authAudience", "value": "${{ secrets.e2e_auth0_audience }}" }]'

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() || failure()
        with:
          files: |
            **/newman-run-*.xml