name: GitHub Actions Demo
on: 
  workflow_dispatch:   
    inputs:
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    environment: 
       name:  ${{ github.event.inputs.environment }}
    steps:
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v3
        with:
              ref: wojtas
      - name: Terraform Plan
        run: |
          terraform plan \
            -var-file="${{ secrets.env_tfvars }}" \
            -no-color
